numero_1=input("Introduce un numero:")
print(type(numero_1))
print("/n")
numero_2=int(input("Introduce otro numero:"))
print(type(numero_2))
print("/n")
numero_3=float(input("Introduce otro numero:"))
print(type(numero_3))